# Ansible Inventory - Generated by Terraform
# DC Automation Project

all:
  children:
    domain_controllers:
      hosts:
        ${server_name}:
          ansible_host: ${dc_server_ip}
          ansible_user: Administrator
          ansible_connection: winrm
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5985
          ansible_winrm_operation_timeout_sec: 240
          ansible_winrm_read_timeout_sec: 300
          
          # Server Configuration
          server_name: ${server_name}
          domain_name: ${domain_name}
          
          # RDS Configuration (if enabled)
          %{ if rds_endpoint != "" ~}
          rds_endpoint: ${rds_endpoint}
          rds_enabled: true
          %{ else ~}
          rds_enabled: false
          %{ endif ~}
          
      vars:
        # Windows-specific Ansible settings
        ansible_shell_type: powershell
        ansible_become_method: runas
        ansible_become_user: Administrator
        
        # Domain Controller specific variables
        dc_role: primary
        forest_mode: WinThreshold
        domain_mode: WinThreshold
        
        # Organizational Units to create
        organizational_units:
          - name: Sales
            path: "DC={{ domain_name | regex_replace('\\.', ',DC=') }}"
          - name: IT
            path: "DC={{ domain_name | regex_replace('\\.', ',DC=') }}"
          - name: HR
            path: "DC={{ domain_name | regex_replace('\\.', ',DC=') }}"
        
        # Users to create (3 per OU + 1 Domain Admin)
        domain_users:
          - name: SalesUser1
            ou: Sales
            groups: []
          - name: SalesUser2
            ou: Sales
            groups: []
          - name: SalesUser3
            ou: Sales
            groups: []
          - name: ITUser1
            ou: IT
            groups: []
          - name: ITUser2
            ou: IT
            groups: []
          - name: ITUser3
            ou: IT
            groups: []
          - name: HRUser1
            ou: HR
            groups: []
          - name: HRUser2
            ou: HR
            groups: []
          - name: HRUser3
            ou: HR
            groups: []
          - name: DomainAdmin
            ou: Users
            groups:
              - Domain Admins
              - Enterprise Admins
        
        # IIS Configuration
        iis_features:
          - IIS-WebServerRole
          - IIS-WebServer
          - IIS-CommonHttpFeatures
          - IIS-HttpErrors
          - IIS-HttpRedirect
          - IIS-ApplicationDevelopment
          - IIS-NetFxExtensibility45
          - IIS-HealthAndDiagnostics
          - IIS-HttpLogging
          - IIS-Security
          - IIS-RequestFiltering
          - IIS-Performance
          - IIS-WebServerManagementTools
          - IIS-ManagementConsole
          - IIS-IIS6ManagementCompatibility
          - IIS-Metabase
        
        # Firewall rules to configure
        firewall_rules:
          - name: "HTTP-In"
            localport: 80
            protocol: tcp
            action: allow
            direction: in
          - name: "HTTPS-In"
            localport: 443
            protocol: tcp
            action: allow
            direction: in
          - name: "DNS-TCP-In"
            localport: 53
            protocol: tcp
            action: allow
            direction: in
          - name: "DNS-UDP-In"
            localport: 53
            protocol: udp
            action: allow
            direction: in
          - name: "LDAP-In"
            localport: 389
            protocol: tcp
            action: allow
            direction: in
          - name: "LDAPS-In"
            localport: 636
            protocol: tcp
            action: allow
            direction: in
          - name: "Kerberos-TCP-In"
            localport: 88
            protocol: tcp
            action: allow
            direction: in
          - name: "Kerberos-UDP-In"
            localport: 88
            protocol: udp
            action: allow
            direction: in
